`timescale 1ns / 1ps
// Vivado project top wrapper (Phase 5 Task 3): keeps the project top name
// while exposing exactly the heatvit_top ports; no logic lives here.
module heatvit (
  input  logic                 clk,
  input  logic                 rst_n,
  input  logic                 start,
  input  logic [31:0]          input_base,
  input  logic [31:0]          input_bytes,
  input  logic [31:0]          weight_base,
  input  logic [31:0]          weight_bytes,
  input  logic [31:0]          scratch_base,
  input  logic [31:0]          scratch_bytes,
  input  logic [31:0]          output_base,
  input  logic [31:0]          output_bytes,
  output logic                 busy,
  output logic                 done,
  output logic                 error_valid,
  output logic [7:0]           error_code,
  output logic [7:0]           warning_flags,
  output logic signed [5:0]    output_scale_exp,
  output logic                 mem_cmd_valid,
  input  logic                 mem_cmd_ready,
  output logic                 mem_cmd_write,
  output logic [31:0]          mem_cmd_addr,
  output logic [15:0]          mem_cmd_len,
  output logic                 mem_w_valid,
  input  logic                 mem_w_ready,
  output logic [63:0]          mem_w_data,
  output logic [7:0]           mem_w_strb,
  output logic                 mem_w_last,
  input  logic                 mem_r_valid,
  output logic                 mem_r_ready,
  input  logic [63:0]          mem_r_data,
  input  logic                 mem_r_last
);

  heatvit_top u_top (
    .clk             (clk),
    .rst_n           (rst_n),
    .start           (start),
    .input_base      (input_base),
    .input_bytes     (input_bytes),
    .weight_base     (weight_base),
    .weight_bytes    (weight_bytes),
    .scratch_base    (scratch_base),
    .scratch_bytes   (scratch_bytes),
    .output_base     (output_base),
    .output_bytes    (output_bytes),
    .busy            (busy),
    .done            (done),
    .error_valid     (error_valid),
    .error_code      (error_code),
    .warning_flags   (warning_flags),
    .output_scale_exp(output_scale_exp),
    .mem_cmd_valid   (mem_cmd_valid),
    .mem_cmd_ready   (mem_cmd_ready),
    .mem_cmd_write   (mem_cmd_write),
    .mem_cmd_addr    (mem_cmd_addr),
    .mem_cmd_len     (mem_cmd_len),
    .mem_w_valid     (mem_w_valid),
    .mem_w_ready     (mem_w_ready),
    .mem_w_data      (mem_w_data),
    .mem_w_strb      (mem_w_strb),
    .mem_w_last      (mem_w_last),
    .mem_r_valid     (mem_r_valid),
    .mem_r_ready     (mem_r_ready),
    .mem_r_data      (mem_r_data),
    .mem_r_last      (mem_r_last)
  );

endmodule
