#!/usr/bin/env python3
"""Generate deterministic Transformer vectors and testbench configuration.

``--case patch`` emits the full 224x224x3 image, [768][192] patch weight,
patch bias, CLS and [197][192] position tensors, the three-descriptor
PATCHIFY -> GEMM -> COPY_ADD_POS sequence, the golden [197][192] activation,
and sim/generated/patch_tb_config.sv for the XSim testbench.
"""

import argparse
import hashlib
import json
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT))

from verification.heatvit_ref.descriptor import (  # noqa: E402
    Descriptor,
    FLAG_BIAS_ENABLE,
    FLAG_AUX_WEIGHT,
    FLAG_DYNAMIC_K,
    FLAG_DYNAMIC_M,
    FLAG_DYNAMIC_N,
    FLAG_HEAD_MODE,
    FLAG_OUTPUT_INT32,
    FLAG_RHS_TRANSPOSE,
    FLAG_SRC1_SCRATCH,
    FLAG_SRC0_INPUT,
    FLAG_SRC0_UNSIGNED,
    OP_COPY_ADD_POS,
    OP_GEMM,
    OP_ATTN_SOFTMAX,
    OP_HEAD_CONCAT,
    OP_LAYERNORM,
    OP_PATCHIFY,
    OP_QKV_UNPACK,
    OP_RESIDUAL,
)
from verification.heatvit_ref.op_sequence import write_descriptors_mem  # noqa: E402
from verification.heatvit_ref.transformer import (  # noqa: E402
    BlockParams,
    FfnParams,
    MhsaParams,
    PatchParams,
    ffn,
    mhsa,
    patch_embedding,
    transformer_block,
)


INPUT_BASE = 0x00000000
WEIGHT_BASE = 0x01000000
SCRATCH_BASE = 0x02000000
OUTPUT_BASE = 0x03000000

IMAGE_BYTES = 224 * 224 * 3
W_BYTES = 768 * 192
BIAS_BYTES = 192 * 4
CLS_BYTES = 192
POS_BYTES = 197 * 192

OFF_W = 0
OFF_BIAS = W_BYTES
OFF_CLS = OFF_BIAS + BIAS_BYTES
OFF_POS = OFF_CLS + CLS_BYTES
WEIGHT_BYTES = OFF_POS + POS_BYTES

OFF_PATCH_MATRIX = 0
OFF_PATCH_EMBED = IMAGE_BYTES
OFF_ACT = OFF_PATCH_EMBED + 196 * 192
SCRATCH_BYTES = OFF_ACT + 197 * 192


def sha256_file(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def pack_int8_bytes(values):
    byte_values = [int(v) & 0xFF for v in values]
    byte_values += [0xA5] * ((-len(byte_values)) % 8)
    words = []
    for i in range(0, len(byte_values), 8):
        word = 0
        for j in range(8):
            word |= byte_values[i + j] << (8 * j)
        words.append(word)
    return words


def pack_int32_bytes(values):
    byte_values = []
    for value in values:
        value = int(value) & 0xFFFFFFFF
        byte_values += [
            value & 0xFF,
            (value >> 8) & 0xFF,
            (value >> 16) & 0xFF,
            (value >> 24) & 0xFF,
        ]
    byte_values += [0xA5] * ((-len(byte_values)) % 8)
    words = []
    for i in range(0, len(byte_values), 8):
        word = 0
        for j in range(8):
            word |= byte_values[i + j] << (8 * j)
        words.append(word)
    return words


def write_mem(path, words):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", newline="\n") as handle:
        for word in words:
            handle.write(f"{word:x}\n")


def write_manifest(outdir, seed, files, descriptors, out_scale):
    manifest = {
        "case": "patch",
        "seed": seed,
        "generator": "tools/generate_transformer_vectors.py",
        "image_bytes": IMAGE_BYTES,
        "weight_bytes": WEIGHT_BYTES,
        "scratch_bytes": SCRATCH_BYTES,
        "activation_offset": OFF_ACT,
        "activation_bytes": 197 * 192,
        "output_scale_exp": out_scale,
        "descriptors": [
            {"opcode": d.opcode, "hex": f"{d.pack():080x}"} for d in descriptors
        ],
        "files": files,
    }
    with open(outdir / "manifest.json", "w", newline="\n") as handle:
        json.dump(manifest, handle, indent=2)
        handle.write("\n")


def write_sv_config(outdir, descriptors):
    lines = []
    lines.append("`ifndef PATCH_TB_CONFIG_PKG_SV")
    lines.append("`define PATCH_TB_CONFIG_PKG_SV")
    lines.append("")
    lines.append("// Generated by tools/generate_transformer_vectors.py; do not edit.")
    lines.append("package patch_tb_config_pkg;")
    lines.append("")
    lines.append(f"  localparam logic [31:0] INPUT_BASE   = 32'h{INPUT_BASE:08x};")
    lines.append(f"  localparam int          INPUT_BYTES  = {IMAGE_BYTES};")
    lines.append(f"  localparam logic [31:0] WEIGHT_BASE  = 32'h{WEIGHT_BASE:08x};")
    lines.append(f"  localparam int          WEIGHT_BYTES = {WEIGHT_BYTES};")
    lines.append(f"  localparam logic [31:0] SCRATCH_BASE = 32'h{SCRATCH_BASE:08x};")
    lines.append(f"  localparam int          SCRATCH_BYTES = {SCRATCH_BYTES};")
    lines.append(f"  localparam logic [31:0] OUTPUT_BASE  = 32'h{OUTPUT_BASE:08x};")
    lines.append("  localparam int          OUTPUT_BYTES = 0;")
    lines.append("")
    for idx, desc in enumerate(descriptors):
        lines.append(f"  localparam logic [319:0] DESC{idx} = 320'h{desc.pack():080x};")
    lines.append("")
    lines.append("  localparam logic signed [5:0] OUT_SCALE = -6'sd7;")
    lines.append(f"  localparam int ACT_OFFSET = {OFF_ACT};")
    lines.append("  localparam int ACT_BYTES  = 37824;")
    lines.append("")
    lines.append("  // Absolute access regions per descriptor for the memory-trace check.")
    trace = [
        ("D0", [(INPUT_BASE, IMAGE_BYTES), (SCRATCH_BASE, IMAGE_BYTES)]),
        (
            "D1",
            [
                (SCRATCH_BASE + OFF_PATCH_MATRIX, IMAGE_BYTES),
                (WEIGHT_BASE + OFF_W, W_BYTES),
                (WEIGHT_BASE + OFF_BIAS, BIAS_BYTES),
                (SCRATCH_BASE + OFF_PATCH_EMBED, 196 * 192),
            ],
        ),
        (
            "D2",
            [
                (SCRATCH_BASE + OFF_PATCH_EMBED, 196 * 192),
                (WEIGHT_BASE + OFF_POS, POS_BYTES),
                (WEIGHT_BASE + OFF_CLS, CLS_BYTES),
                (SCRATCH_BASE + OFF_ACT, 197 * 192),
            ],
        ),
    ]
    for prefix, regions in trace:
        for idx, (base, size) in enumerate(regions):
            lines.append(
                f"  localparam logic [31:0] {prefix}_R{idx}_BASE  = 32'h{base:08x};"
            )
            lines.append(f"  localparam int          {prefix}_R{idx}_BYTES = {size};")
    lines.append("")
    lines.append("endpackage")
    lines.append("")
    lines.append("`endif")

    config_path = REPO_ROOT / "sim" / "generated" / "patch_tb_config.sv"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def generate_patch(seed, outdir):
    rng = np.random.default_rng(seed)
    image = rng.integers(-128, 128, size=224 * 224 * 3, dtype=np.int64)
    weight = rng.integers(-8, 8, size=(768, 192), dtype=np.int64)
    bias = rng.integers(-64, 64, size=192, dtype=np.int64)
    cls = rng.integers(-128, 128, size=192, dtype=np.int64)
    pos = rng.integers(-128, 128, size=(197, 192), dtype=np.int64)

    params = PatchParams(
        patch_weight=[list(row) for row in weight],
        patch_bias=[int(v) for v in bias],
        cls=[int(v) for v in cls],
        pos=[list(row) for row in pos],
    )
    activation = patch_embedding([int(v) for v in image], params)

    descriptors = [
        Descriptor(
            opcode=OP_PATCHIFY,
            flags=1 << FLAG_SRC0_INPUT,
            m=196,
            n=768,
            src0_offset=0,
            dst_offset=OFF_PATCH_MATRIX,
            src0_scale_exp=-7,
            dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_GEMM,
            flags=1 << FLAG_BIAS_ENABLE,
            m=196,
            n=192,
            k=768,
            src0_offset=OFF_PATCH_MATRIX,
            src1_offset=OFF_W,
            bias_offset=OFF_BIAS,
            dst_offset=OFF_PATCH_EMBED,
            src0_scale_exp=-7,
            src1_scale_exp=-7,
            dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_COPY_ADD_POS,
            flags=1 << FLAG_AUX_WEIGHT,
            m=197,
            n=192,
            src0_offset=OFF_PATCH_EMBED,
            src1_offset=OFF_POS,
            aux_offset=OFF_CLS,
            dst_offset=OFF_ACT,
            src0_scale_exp=-7,
            src1_scale_exp=-7,
            aux_scale_exp=-7,
            dst_scale_exp=-7,
        ),
    ]

    image_path = outdir / "image.mem"
    write_mem(image_path, pack_int8_bytes([int(v) for v in image]))

    weight_bytes = []
    weight_bytes += [int(v) for v in weight.ravel()]
    weight_bytes += [0] * ((-len(weight_bytes)) % 8)
    weight_words = pack_int8_bytes(weight_bytes)[:]  # W block, then bias/cls/pos
    bias_words = pack_int32_bytes([int(v) for v in bias])
    cls_words = pack_int8_bytes([int(v) for v in cls])
    pos_words = pack_int8_bytes([int(v) for v in pos.ravel()])
    weight_path = outdir / "weight.mem"
    write_mem(weight_path, weight_words + bias_words + cls_words + pos_words)

    expected_path = outdir / "expected.mem"
    write_mem(expected_path, pack_int8_bytes(
        [v for row in activation for v in row]))

    write_sv_config(outdir, descriptors)

    files = [
        {
            "name": "image.mem",
            "records": len(pack_int8_bytes([int(v) for v in image])),
            "sha256": sha256_file(image_path),
        },
        {
            "name": "weight.mem",
            "records": len(weight_words) + len(bias_words) + len(cls_words) + len(pos_words),
            "sha256": sha256_file(weight_path),
        },
        {
            "name": "expected.mem",
            "records": len(pack_int8_bytes([v for row in activation for v in row])),
            "sha256": sha256_file(expected_path),
        },
    ]
    write_manifest(outdir, seed, files, descriptors, -7)


def align8(value):
    return (value + 7) & ~7


def _flag(*bits):
    value = 0
    for bit in bits:
        value |= 1 << bit
    return value


def write_mhsa_sv_config(outdir, tokens, offsets, descriptors, regions):
    lines = []
    lines.append("`ifndef MHSA_TB_CONFIG_PKG_SV")
    lines.append("`define MHSA_TB_CONFIG_PKG_SV")
    lines.append("")
    lines.append("// Generated by tools/generate_transformer_vectors.py; do not edit.")
    lines.append("package mhsa_tb_config_pkg;")
    lines.append("")
    lines.append(f"  localparam int N = {tokens};")
    lines.append(f"  localparam logic [31:0] WEIGHT_BASE  = 32'h{WEIGHT_BASE:08x};")
    lines.append(f"  localparam int          WEIGHT_BYTES = {offsets['weight_bytes']};")
    lines.append(f"  localparam logic [31:0] SCRATCH_BASE = 32'h{SCRATCH_BASE:08x};")
    lines.append(f"  localparam int          SCRATCH_BYTES = {offsets['scratch_bytes']};")
    for key in ("x", "ln1", "fused", "qkv", "score", "prob", "context", "concat", "msa"):
        lines.append(f"  localparam int {key.upper()}_OFF = {offsets[key + '_off']};")
    lines.append(f"  localparam int QKV_BYTES = {576 * tokens};")
    lines.append(f"  localparam int SCORE_BYTES = {12 * tokens * tokens};")
    lines.append(f"  localparam int PROB_BYTES = {3 * tokens * tokens};")
    lines.append(f"  localparam int CONTEXT_BYTES = {192 * tokens};")
    lines.append(f"  localparam int CONCAT_BYTES = {192 * tokens};")
    lines.append(f"  localparam int MSA_BYTES = {192 * tokens};")
    lines.append("")
    for idx, desc in enumerate(descriptors):
        lines.append(f"  localparam logic [319:0] DESC{idx} = 320'h{desc.pack():080x};")
    lines.append("")
    lines.append("  localparam logic signed [5:0] OUT_SCALE   = -6'sd7;")
    lines.append("  localparam logic signed [5:0] SCORE_SCALE = -6'sd17;")
    lines.append("  localparam logic signed [5:0] PROB_SCALE  = -6'sd8;")
    lines.append("")
    for idx, desc_regions in enumerate(regions):
        for r, (base, size) in enumerate(desc_regions):
            lines.append(
                f"  localparam logic [31:0] D{idx}_R{r}_BASE  = 32'h{base:08x};"
            )
            lines.append(f"  localparam int          D{idx}_R{r}_BYTES = {size};")
    lines.append("")
    lines.append("endpackage")
    lines.append("")
    lines.append("`endif")

    config_path = REPO_ROOT / "sim" / "generated" / "mhsa_tb_config.sv"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def generate_mhsa(seed, tokens, outdir):
    rng = np.random.default_rng(seed)
    n = tokens
    if n < 2 or n > 197:
        raise ValueError("tokens must be in [2, 197]")

    # Token 0 is 64-hot in the head lanes; later tokens are hot outside so
    # head 0 keeps one dominant score row and at least one prob equals 128.
    x = []
    for t in range(n):
        row = [0] * 192
        if t == 0:
            for c in range(64):
                row[c] = 127
        else:
            row[64 + (t - 1) % 128] = 127
        x.append(row)

    ln_gamma = [64] * 192
    ln_beta = [0] * 192
    wqkv = [[0] * 576 for _ in range(192)]
    for lane in range(64):
        wqkv[lane][lane] = 1
        wqkv[lane][64 + lane] = 1
        wqkv[lane][128 + lane] = 1
        wqkv[lane][192 + lane] = 1
        wqkv[lane][256 + lane] = -1
        wqkv[lane][320 + lane] = 1 if lane % 2 == 0 else -1
        wqkv[lane][384 + lane] = 1
        wqkv[lane][448 + lane] = 1
        wqkv[lane][512 + lane] = 1
    bqkv = [0] * 576
    wproj = [
        [int(v) for v in row]
        for row in rng.integers(-8, 8, size=(192, 192), dtype=np.int64)
    ]
    bproj = [int(v) for v in rng.integers(-64, 64, size=192, dtype=np.int64)]

    params = MhsaParams(
        ln_gamma=ln_gamma,
        ln_beta=ln_beta,
        wqkv=wqkv,
        bqkv=bqkv,
        wproj=wproj,
        bproj=bproj,
        wqkv_scale_exp=0,
        wproj_scale_exp=0,
    )
    output, checkpoints = mhsa(x, params)

    # Scratch arena with 8-byte alignment.
    x_off = 0
    ln1_off = align8(x_off + 192 * n)
    fused_off = align8(ln1_off + 192 * n)
    qkv_off = align8(fused_off + 576 * n)
    score_off = align8(qkv_off + 576 * n)
    prob_off = align8(score_off + 12 * n * n)
    context_off = align8(prob_off + 3 * n * n)
    concat_off = align8(context_off + 192 * n)
    msa_off = align8(concat_off + 192 * n)
    scratch_bytes = align8(msa_off + 192 * n)

    # Weight arena.
    wqkv_off = 0
    bqkv_off = wqkv_off + 110592
    wproj_off = bqkv_off + 2304
    bproj_off = wproj_off + 36864
    gamma_off = bproj_off + 768
    beta_off = gamma_off + 192
    weight_bytes = beta_off + 192

    descriptors = [
        Descriptor(
            opcode=OP_LAYERNORM, flags=_flag(FLAG_DYNAMIC_M, FLAG_AUX_WEIGHT),
            m=99, n=192, param0=0,
            src0_offset=x_off, src1_offset=gamma_off, aux_offset=beta_off,
            dst_offset=ln1_off,
            src0_scale_exp=-7, src1_scale_exp=-6, aux_scale_exp=-7,
            dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_GEMM, flags=_flag(FLAG_BIAS_ENABLE, FLAG_DYNAMIC_M),
            m=99, n=576, k=192, param0=0,
            src0_offset=ln1_off, src1_offset=wqkv_off, bias_offset=bqkv_off,
            dst_offset=fused_off,
            src0_scale_exp=-7, src1_scale_exp=0, dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_QKV_UNPACK, flags=_flag(FLAG_DYNAMIC_M),
            m=99, n=576, heads=3, param0=0,
            src0_offset=fused_off, dst_offset=qkv_off,
        ),
        Descriptor(
            opcode=OP_GEMM,
            flags=_flag(FLAG_RHS_TRANSPOSE, FLAG_HEAD_MODE, FLAG_OUTPUT_INT32,
                        FLAG_DYNAMIC_M, FLAG_DYNAMIC_N, FLAG_SRC1_SCRATCH),
            m=99, n=99, k=64, heads=3, param0=0,
            src0_offset=qkv_off, src1_offset=qkv_off + 192 * n,
            dst_offset=score_off,
            src0_scale_exp=-7, src1_scale_exp=-7, dst_scale_exp=-17,
        ),
        Descriptor(
            opcode=OP_ATTN_SOFTMAX, flags=_flag(FLAG_DYNAMIC_M, FLAG_DYNAMIC_N),
            m=99, n=99, heads=3, param0=0,
            src0_offset=score_off, dst_offset=prob_off,
            # P2 fix: s0 = -20 adds the 1/sqrt(64) (3 extra bits) to the
            # Q8.16 requant (was -17).
            src0_scale_exp=-20,
        ),
        Descriptor(
            opcode=OP_GEMM,
            flags=_flag(FLAG_HEAD_MODE, FLAG_SRC0_UNSIGNED,
                        FLAG_DYNAMIC_M, FLAG_DYNAMIC_K, FLAG_SRC1_SCRATCH),
            m=99, n=64, k=99, heads=3, param0=0,
            src0_offset=prob_off, src1_offset=qkv_off + 384 * n,
            dst_offset=context_off,
            src0_scale_exp=-8, src1_scale_exp=-7, dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_HEAD_CONCAT, flags=_flag(FLAG_DYNAMIC_M),
            m=99, n=192, heads=3, param0=0,
            src0_offset=context_off, dst_offset=concat_off,
        ),
        Descriptor(
            opcode=OP_GEMM, flags=_flag(FLAG_BIAS_ENABLE, FLAG_DYNAMIC_M),
            m=99, n=192, k=192, param0=0,
            src0_offset=concat_off, src1_offset=wproj_off, bias_offset=bproj_off,
            dst_offset=msa_off,
            src0_scale_exp=-7, src1_scale_exp=0, dst_scale_exp=-7,
        ),
    ]

    # Per-descriptor trace regions (absolute bases).
    sb = SCRATCH_BASE
    wb = WEIGHT_BASE
    regions = [
        [(sb + x_off, 192 * n), (wb + gamma_off, 192), (wb + beta_off, 192),
         (sb + ln1_off, 192 * n)],
        [(sb + ln1_off, 192 * n), (wb + wqkv_off, 110592),
         (wb + bqkv_off, 2304), (sb + fused_off, 576 * n)],
        [(sb + fused_off, 576 * n), (sb + qkv_off, 576 * n)],
        [(sb + qkv_off, 192 * n), (sb + qkv_off + 192 * n, 192 * n),
         (sb + score_off, align8(12 * n * n))],
        [(sb + score_off, align8(12 * n * n)), (sb + prob_off, align8(3 * n * n))],
        [(sb + prob_off, align8(3 * n * n)), (sb + qkv_off + 384 * n, 192 * n),
         (sb + context_off, 192 * n)],
        [(sb + context_off, 192 * n), (sb + concat_off, 192 * n)],
        [(sb + concat_off, 192 * n), (wb + wproj_off, 36864),
         (wb + bproj_off, 768), (sb + msa_off, 192 * n)],
    ]

    # Packed inputs and checkpoints.
    x_path = outdir / "x.mem"
    write_mem(x_path, pack_int8_bytes([v for row in x for v in row]))

    weight_values = [v for row in wqkv for v in row]
    weight_values += [0] * ((-len(weight_values)) % 8)
    weight_path = outdir / "weight.mem"
    write_mem(
        weight_path,
        pack_int8_bytes(weight_values)
        + pack_int32_bytes(bqkv)
        + pack_int8_bytes([v for row in wproj for v in row])
        + pack_int32_bytes(bproj)
        + pack_int8_bytes(ln_gamma)
        + pack_int8_bytes(ln_beta),
    )

    qkv_flat = [
        v
        for kind in checkpoints["qkv"]
        for head in kind
        for token in head
        for v in token
    ]
    score_flat = [
        v for head in checkpoints["score"] for row in head for v in row
    ]
    prob_flat = [
        v for head in checkpoints["prob"] for row in head for v in row
    ]
    context_flat = [
        v for head in checkpoints["context"] for row in head for v in row
    ]
    concat_flat = [v for row in checkpoints["concat"] for v in row]
    msa_flat = [v for row in output for v in row]

    checkpoint_paths = {
        "qkv": outdir / "qkv_expected.mem",
        "score": outdir / "score_expected.mem",
        "prob": outdir / "prob_expected.mem",
        "context": outdir / "context_expected.mem",
        "concat": outdir / "concat_expected.mem",
        "msa": outdir / "msa_expected.mem",
    }
    write_mem(checkpoint_paths["qkv"], pack_int8_bytes(qkv_flat))
    write_mem(checkpoint_paths["score"], pack_int32_bytes(score_flat))
    write_mem(checkpoint_paths["prob"], pack_int8_bytes(prob_flat))
    write_mem(checkpoint_paths["context"], pack_int8_bytes(context_flat))
    write_mem(checkpoint_paths["concat"], pack_int8_bytes(concat_flat))
    write_mem(checkpoint_paths["msa"], pack_int8_bytes(msa_flat))

    offsets = {
        "x_off": x_off,
        "ln1_off": ln1_off,
        "fused_off": fused_off,
        "qkv_off": qkv_off,
        "score_off": score_off,
        "prob_off": prob_off,
        "context_off": context_off,
        "concat_off": concat_off,
        "msa_off": msa_off,
        "scratch_bytes": scratch_bytes,
        "weight_bytes": weight_bytes,
    }
    write_mhsa_sv_config(outdir, tokens, offsets, descriptors, regions)

    files = [
        {"name": p.name, "records": len(
            pack_int8_bytes([v for row in x for v in row])), "sha256": sha256_file(p)}
        if p.name == "x.mem" else
        {"name": p.name, "records": 0, "sha256": sha256_file(p)}
        for p in [x_path, weight_path]
    ]
    files += [
        {"name": p.name, "records": 0, "sha256": sha256_file(p)}
        for p in checkpoint_paths.values()
    ]
    manifest = {
        "case": "mhsa",
        "seed": seed,
        "tokens": tokens,
        "generator": "tools/generate_transformer_vectors.py",
        "weight_bytes": weight_bytes,
        "scratch_bytes": scratch_bytes,
        "scales": {"activation": -7, "score": -17, "prob": -8, "weight": 0},
        "descriptors": [
            {"opcode": d.opcode, "hex": f"{d.pack():080x}"} for d in descriptors
        ],
        "files": files,
    }
    with open(outdir / "manifest.json", "w", newline="\n") as handle:
        json.dump(manifest, handle, indent=2)
        handle.write("\n")


def write_ffn_sv_config(outdir, tokens, offsets, descriptors, regions):
    lines = []
    lines.append("`ifndef FFN_TB_CONFIG_PKG_SV")
    lines.append("`define FFN_TB_CONFIG_PKG_SV")
    lines.append("")
    lines.append("// Generated by tools/generate_transformer_vectors.py; do not edit.")
    lines.append("package ffn_tb_config_pkg;")
    lines.append("")
    lines.append(f"  localparam int N = {tokens};")
    lines.append(f"  localparam logic [31:0] WEIGHT_BASE  = 32'h{WEIGHT_BASE:08x};")
    lines.append(f"  localparam int          WEIGHT_BYTES = {offsets['weight_bytes']};")
    lines.append(f"  localparam logic [31:0] SCRATCH_BASE = 32'h{SCRATCH_BASE:08x};")
    lines.append(f"  localparam int          SCRATCH_BYTES = {offsets['scratch_bytes']};")
    for key in ("y", "ln2", "hidden", "ffn_out", "z"):
        lines.append(f"  localparam int {key.upper()}_OFF = {offsets[key + '_off']};")
    lines.append(f"  localparam int LN2_BYTES = {192 * tokens};")
    lines.append(f"  localparam int HIDDEN_BYTES = {768 * tokens};")
    lines.append(f"  localparam int FFN_OUT_BYTES = {192 * tokens};")
    lines.append(f"  localparam int Z_ROWS = {(tokens + 7) // 8 * 8};")
    lines.append(f"  localparam int Z_BYTES = {192 * ((tokens + 7) // 8 * 8)};")
    lines.append(f"  localparam int Z_PAD_OFF = {offsets['z_off'] + 192 * tokens};")
    lines.append(f"  localparam int Z_PAD_BYTES = {192 * ((tokens + 7) // 8 * 8 - tokens)};")
    lines.append("")
    for idx, desc in enumerate(descriptors):
        lines.append(f"  localparam logic [319:0] DESC{idx} = 320'h{desc.pack():080x};")
    lines.append("")
    for idx, desc_regions in enumerate(regions):
        for r, (base, size) in enumerate(desc_regions):
            lines.append(
                f"  localparam logic [31:0] D{idx}_R{r}_BASE  = 32'h{base:08x};"
            )
            lines.append(f"  localparam int          D{idx}_R{r}_BYTES = {size};")
    lines.append("")
    lines.append("endpackage")
    lines.append("")
    lines.append("`endif")

    config_path = REPO_ROOT / "sim" / "generated" / "ffn_tb_config.sv"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def generate_ffn(seed, tokens, outdir):
    rng = np.random.default_rng(seed)
    n = tokens
    if n < 2 or n > 197:
        raise ValueError("tokens must be in [2, 197]")

    y = [
        [int(v) for v in row]
        for row in rng.integers(-128, 128, size=(n, 192), dtype=np.int64)
    ]
    ln_gamma = [int(v) for v in rng.integers(0, 128, size=192)]
    ln_beta = [int(v) for v in rng.integers(-32, 32, size=192)]
    w1 = [
        [int(v) for v in row]
        for row in rng.integers(-128, 128, size=(192, 768), dtype=np.int64)
    ]
    w1[0][0] = 127
    w1[0][1] = -128
    b1 = [int(v) for v in rng.integers(-64, 64, size=768)]
    w2 = [
        [int(v) for v in row]
        for row in rng.integers(-128, 128, size=(768, 192), dtype=np.int64)
    ]
    b2 = [int(v) for v in rng.integers(-64, 64, size=192)]

    params = FfnParams(
        ln_gamma=ln_gamma,
        ln_beta=ln_beta,
        w1=w1,
        b1=b1,
        w2=w2,
        b2=b2,
        w1_scale_exp=0,
        w2_scale_exp=0,
    )
    z, checkpoints = ffn(y, params)

    y_off = 0
    ln2_off = align8(y_off + 192 * n)
    hidden_off = align8(ln2_off + 192 * n)
    ffn_out_off = align8(hidden_off + 768 * n)
    z_off = align8(ffn_out_off + 192 * n)
    z_rows = (n + 7) // 8 * 8
    scratch_bytes = align8(z_off + 192 * z_rows)

    w1_off = 0
    b1_off = w1_off + 147456
    w2_off = b1_off + 3072
    b2_off = w2_off + 147456
    gamma_off = b2_off + 768
    beta_off = gamma_off + 192
    weight_bytes = beta_off + 192

    descriptors = [
        Descriptor(
            opcode=OP_LAYERNORM, flags=_flag(FLAG_DYNAMIC_M, FLAG_AUX_WEIGHT),
            m=99, n=192, param0=0,
            src0_offset=y_off, src1_offset=gamma_off, aux_offset=beta_off,
            dst_offset=ln2_off,
            src0_scale_exp=-7, src1_scale_exp=-6, aux_scale_exp=-7,
            dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_GEMM,
            flags=_flag(FLAG_BIAS_ENABLE, FLAG_DYNAMIC_M) | (2 << 8),
            m=99, n=768, k=192, param0=0,
            src0_offset=ln2_off, src1_offset=w1_off, bias_offset=b1_off,
            dst_offset=hidden_off,
            src0_scale_exp=-7, src1_scale_exp=0, dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_GEMM, flags=_flag(FLAG_BIAS_ENABLE, FLAG_DYNAMIC_M),
            m=99, n=192, k=768, param0=0,
            src0_offset=hidden_off, src1_offset=w2_off, bias_offset=b2_off,
            dst_offset=ffn_out_off,
            src0_scale_exp=-7, src1_scale_exp=0, dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_RESIDUAL, flags=_flag(FLAG_DYNAMIC_M),
            m=99, n=192, param0=0,
            src0_offset=y_off, aux_offset=ffn_out_off, dst_offset=z_off,
            src0_scale_exp=-7, aux_scale_exp=-7, dst_scale_exp=-7,
        ),
    ]

    sb = SCRATCH_BASE
    wb = WEIGHT_BASE
    regions = [
        [(sb + y_off, 192 * n), (wb + gamma_off, 192), (wb + beta_off, 192),
         (sb + ln2_off, 192 * n)],
        [(sb + ln2_off, 192 * n), (wb + w1_off, 147456),
         (wb + b1_off, 3072), (sb + hidden_off, 768 * n)],
        [(sb + hidden_off, 768 * n), (wb + w2_off, 147456),
         (wb + b2_off, 768), (sb + ffn_out_off, 192 * n)],
        [(sb + y_off, 192 * n), (sb + ffn_out_off, 192 * n),
         (sb + z_off, 192 * z_rows)],
    ]

    offsets = {
        "y_off": y_off,
        "ln2_off": ln2_off,
        "hidden_off": hidden_off,
        "ffn_out_off": ffn_out_off,
        "z_off": z_off,
        "scratch_bytes": scratch_bytes,
        "weight_bytes": weight_bytes,
    }
    write_ffn_sv_config(outdir, tokens, offsets, descriptors, regions)

    y_path = outdir / "y.mem"
    write_mem(y_path, pack_int8_bytes([v for row in y for v in row]))

    weight_path = outdir / "weight.mem"
    write_mem(
        weight_path,
        pack_int8_bytes([v for row in w1 for v in row])
        + pack_int32_bytes(b1)
        + pack_int8_bytes([v for row in w2 for v in row])
        + pack_int32_bytes(b2)
        + pack_int8_bytes(ln_gamma)
        + pack_int8_bytes(ln_beta),
    )

    ln2_flat = [v for row in checkpoints["ln2"] for v in row]
    hidden_flat = [v for row in checkpoints["hidden"] for v in row]
    ffn_out_flat = [v for row in checkpoints["ffn_out"] for v in row]
    z_flat = [v for row in z for v in row] + [0xA5] * (192 * (z_rows - n))

    checkpoint_paths = {
        "ln2": outdir / "ln2_expected.mem",
        "hidden": outdir / "hidden_expected.mem",
        "ffn_out": outdir / "ffn_out_expected.mem",
        "z": outdir / "z_expected.mem",
    }
    write_mem(checkpoint_paths["ln2"], pack_int8_bytes(ln2_flat))
    write_mem(checkpoint_paths["hidden"], pack_int8_bytes(hidden_flat))
    write_mem(checkpoint_paths["ffn_out"], pack_int8_bytes(ffn_out_flat))
    write_mem(checkpoint_paths["z"], pack_int8_bytes(z_flat))

    files = [
        {"name": "y.mem", "records": len(pack_int8_bytes(
            [v for row in y for v in row])), "sha256": sha256_file(y_path)},
        {"name": "weight.mem", "records": 0, "sha256": sha256_file(weight_path)},
    ]
    files += [
        {"name": p.name, "records": 0, "sha256": sha256_file(p)}
        for p in checkpoint_paths.values()
    ]
    manifest = {
        "case": "ffn",
        "seed": seed,
        "tokens": tokens,
        "generator": "tools/generate_transformer_vectors.py",
        "weight_bytes": weight_bytes,
        "scratch_bytes": scratch_bytes,
        "z_rows": z_rows,
        "scales": {"activation": -7, "weight": 0},
        "descriptors": [
            {"opcode": d.opcode, "hex": f"{d.pack():080x}"} for d in descriptors
        ],
        "files": files,
    }
    with open(outdir / "manifest.json", "w", newline="\n") as handle:
        json.dump(manifest, handle, indent=2)
        handle.write("\n")


def _block_scratch_offsets(n, start, z_rows):
    offs = {}
    offs["x"] = start
    offs["ln1"] = align8(offs["x"] + 192 * n)
    offs["fused"] = align8(offs["ln1"] + 192 * n)
    offs["qkv"] = align8(offs["fused"] + 576 * n)
    offs["score"] = align8(offs["qkv"] + 576 * n)
    offs["prob"] = align8(offs["score"] + 12 * n * n)
    offs["context"] = align8(offs["prob"] + 3 * n * n)
    offs["concat"] = align8(offs["context"] + 192 * n)
    offs["msa"] = align8(offs["concat"] + 192 * n)
    offs["y"] = align8(offs["msa"] + 192 * n)
    offs["ln2"] = align8(offs["y"] + 192 * n)
    offs["hidden"] = align8(offs["ln2"] + 192 * n)
    offs["ffn_out"] = align8(offs["hidden"] + 768 * n)
    offs["z"] = align8(offs["ffn_out"] + 192 * n)
    offs["z_rows_bytes"] = 192 * z_rows
    return offs


def _block_weight_offsets():
    offs = {}
    cur = 0
    layout = (
        ("wqkv", 110592),
        ("bqkv", 2304),
        ("wproj", 36864),
        ("bproj", 768),
        ("gamma1", 192),
        ("beta1", 192),
        ("w1", 147456),
        ("b1", 3072),
        ("w2", 147456),
        ("b2", 768),
        ("gamma2", 192),
        ("beta2", 192),
    )
    for block in (0, 1):
        for name, size in layout:
            offs[f"{name}{block}"] = cur
            cur += size
    return offs, cur


def _random_block_params(rng):
    mhsa_params = MhsaParams(
        ln_gamma=[int(v) for v in rng.integers(0, 128, size=192)],
        ln_beta=[int(v) for v in rng.integers(-32, 32, size=192)],
        wqkv=[
            [int(v) for v in row]
            for row in rng.integers(-8, 8, size=(192, 576), dtype=np.int64)
        ],
        bqkv=[int(v) for v in rng.integers(-64, 64, size=576)],
        wproj=[
            [int(v) for v in row]
            for row in rng.integers(-8, 8, size=(192, 192), dtype=np.int64)
        ],
        bproj=[int(v) for v in rng.integers(-64, 64, size=192)],
        wqkv_scale_exp=0,
        wproj_scale_exp=0,
    )
    ffn_params = FfnParams(
        ln_gamma=[int(v) for v in rng.integers(0, 128, size=192)],
        ln_beta=[int(v) for v in rng.integers(-32, 32, size=192)],
        w1=[
            [int(v) for v in row]
            for row in rng.integers(-128, 128, size=(192, 768), dtype=np.int64)
        ],
        b1=[int(v) for v in rng.integers(-64, 64, size=768)],
        w2=[
            [int(v) for v in row]
            for row in rng.integers(-128, 128, size=(768, 192), dtype=np.int64)
        ],
        b2=[int(v) for v in rng.integers(-64, 64, size=192)],
        w1_scale_exp=0,
        w2_scale_exp=0,
    )
    return BlockParams(mhsa=mhsa_params, ffn=ffn_params)


def _block_descriptors(n, scratch, weight):
    return [
        Descriptor(
            opcode=OP_LAYERNORM, flags=_flag(FLAG_DYNAMIC_M, FLAG_AUX_WEIGHT),
            m=99, n=192, param0=0,
            src0_offset=scratch["x"], src1_offset=weight["gamma1"],
            aux_offset=weight["beta1"], dst_offset=scratch["ln1"],
            src0_scale_exp=-7, src1_scale_exp=-6, aux_scale_exp=-7,
            dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_GEMM, flags=_flag(FLAG_BIAS_ENABLE, FLAG_DYNAMIC_M),
            m=99, n=576, k=192, param0=0,
            src0_offset=scratch["ln1"], src1_offset=weight["wqkv"],
            bias_offset=weight["bqkv"], dst_offset=scratch["fused"],
            src0_scale_exp=-7, src1_scale_exp=0, dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_QKV_UNPACK, flags=_flag(FLAG_DYNAMIC_M),
            m=99, n=576, heads=3, param0=0,
            src0_offset=scratch["fused"], dst_offset=scratch["qkv"],
        ),
        Descriptor(
            opcode=OP_GEMM,
            flags=_flag(FLAG_RHS_TRANSPOSE, FLAG_HEAD_MODE, FLAG_OUTPUT_INT32,
                        FLAG_DYNAMIC_M, FLAG_DYNAMIC_N, FLAG_SRC1_SCRATCH),
            m=99, n=99, k=64, heads=3, param0=0,
            src0_offset=scratch["qkv"],
            src1_offset=scratch["qkv"] + 192 * n,
            dst_offset=scratch["score"],
            src0_scale_exp=-7, src1_scale_exp=-7, dst_scale_exp=-17,
        ),
        Descriptor(
            opcode=OP_ATTN_SOFTMAX, flags=_flag(FLAG_DYNAMIC_M, FLAG_DYNAMIC_N),
            m=99, n=99, heads=3, param0=0,
            src0_offset=scratch["score"], dst_offset=scratch["prob"],
            # P2 fix: s0 = -20 adds the 1/sqrt(64) (3 extra bits) to the
            # Q8.16 requant (was -17).
            src0_scale_exp=-20,
        ),
        Descriptor(
            opcode=OP_GEMM,
            flags=_flag(FLAG_HEAD_MODE, FLAG_SRC0_UNSIGNED,
                        FLAG_DYNAMIC_M, FLAG_DYNAMIC_K, FLAG_SRC1_SCRATCH),
            m=99, n=64, k=99, heads=3, param0=0,
            src0_offset=scratch["prob"],
            src1_offset=scratch["qkv"] + 384 * n,
            dst_offset=scratch["context"],
            src0_scale_exp=-8, src1_scale_exp=-7, dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_HEAD_CONCAT, flags=_flag(FLAG_DYNAMIC_M),
            m=99, n=192, heads=3, param0=0,
            src0_offset=scratch["context"], dst_offset=scratch["concat"],
        ),
        Descriptor(
            opcode=OP_GEMM, flags=_flag(FLAG_BIAS_ENABLE, FLAG_DYNAMIC_M),
            m=99, n=192, k=192, param0=0,
            src0_offset=scratch["concat"], src1_offset=weight["wproj"],
            bias_offset=weight["bproj"], dst_offset=scratch["msa"],
            src0_scale_exp=-7, src1_scale_exp=0, dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_RESIDUAL, flags=_flag(FLAG_DYNAMIC_M),
            m=99, n=192, param0=0,
            src0_offset=scratch["x"], aux_offset=scratch["msa"],
            dst_offset=scratch["y"],
            src0_scale_exp=-7, aux_scale_exp=-7, dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_LAYERNORM, flags=_flag(FLAG_DYNAMIC_M, FLAG_AUX_WEIGHT),
            m=99, n=192, param0=0,
            src0_offset=scratch["y"], src1_offset=weight["gamma2"],
            aux_offset=weight["beta2"], dst_offset=scratch["ln2"],
            src0_scale_exp=-7, src1_scale_exp=-6, aux_scale_exp=-7,
            dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_GEMM,
            flags=_flag(FLAG_BIAS_ENABLE, FLAG_DYNAMIC_M) | (2 << 8),
            m=99, n=768, k=192, param0=0,
            src0_offset=scratch["ln2"], src1_offset=weight["w1"],
            bias_offset=weight["b1"], dst_offset=scratch["hidden"],
            src0_scale_exp=-7, src1_scale_exp=0, dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_GEMM, flags=_flag(FLAG_BIAS_ENABLE, FLAG_DYNAMIC_M),
            m=99, n=192, k=768, param0=0,
            src0_offset=scratch["hidden"], src1_offset=weight["w2"],
            bias_offset=weight["b2"], dst_offset=scratch["ffn_out"],
            src0_scale_exp=-7, src1_scale_exp=0, dst_scale_exp=-7,
        ),
        Descriptor(
            opcode=OP_RESIDUAL, flags=_flag(FLAG_DYNAMIC_M),
            m=99, n=192, param0=0,
            src0_offset=scratch["y"], aux_offset=scratch["ffn_out"],
            dst_offset=scratch["z"],
            src0_scale_exp=-7, aux_scale_exp=-7, dst_scale_exp=-7,
        ),
    ]


def _block_regions(n, scratch, weight, z_rows):
    sb = SCRATCH_BASE
    wb = WEIGHT_BASE
    return [
        [(sb + scratch["x"], 192 * n), (wb + weight["gamma1"], 192),
         (wb + weight["beta1"], 192), (sb + scratch["ln1"], 192 * n)],
        [(sb + scratch["ln1"], 192 * n), (wb + weight["wqkv"], 110592),
         (wb + weight["bqkv"], 2304), (sb + scratch["fused"], 576 * n)],
        [(sb + scratch["fused"], 576 * n), (sb + scratch["qkv"], 576 * n)],
        [(sb + scratch["qkv"], 192 * n),
         (sb + scratch["qkv"] + 192 * n, 192 * n),
         (sb + scratch["score"], align8(12 * n * n))],
        [(sb + scratch["score"], align8(12 * n * n)),
         (sb + scratch["prob"], align8(3 * n * n))],
        [(sb + scratch["prob"], align8(3 * n * n)),
         (sb + scratch["qkv"] + 384 * n, 192 * n),
         (sb + scratch["context"], 192 * n)],
        [(sb + scratch["context"], 192 * n), (sb + scratch["concat"], 192 * n)],
        [(sb + scratch["concat"], 192 * n), (wb + weight["wproj"], 36864),
         (wb + weight["bproj"], 768), (sb + scratch["msa"], 192 * n)],
        [(sb + scratch["x"], 192 * n), (sb + scratch["msa"], 192 * n),
         (sb + scratch["y"], 192 * n)],
        [(sb + scratch["y"], 192 * n), (wb + weight["gamma2"], 192),
         (wb + weight["beta2"], 192), (sb + scratch["ln2"], 192 * n)],
        [(sb + scratch["ln2"], 192 * n), (wb + weight["w1"], 147456),
         (wb + weight["b1"], 3072), (sb + scratch["hidden"], 768 * n)],
        [(sb + scratch["hidden"], 768 * n), (wb + weight["w2"], 147456),
         (wb + weight["b2"], 768), (sb + scratch["ffn_out"], 192 * n)],
        [(sb + scratch["y"], 192 * n), (sb + scratch["ffn_out"], 192 * n),
         (sb + scratch["z"], 192 * z_rows)],
    ]


def write_block_sv_config(outdir, tokens, offsets, descriptors, regions):
    z_rows = (tokens + 7) // 8 * 8
    lines = []
    lines.append("`ifndef BLOCK_TB_CONFIG_PKG_SV")
    lines.append("`define BLOCK_TB_CONFIG_PKG_SV")
    lines.append("")
    lines.append("// Generated by tools/generate_transformer_vectors.py; do not edit.")
    lines.append("package block_tb_config_pkg;")
    lines.append("")
    lines.append(f"  localparam int N = {tokens};")
    lines.append(f"  localparam logic [31:0] WEIGHT_BASE  = 32'h{WEIGHT_BASE:08x};")
    lines.append(f"  localparam int          WEIGHT_BYTES = {offsets['weight_bytes']};")
    lines.append(f"  localparam logic [31:0] SCRATCH_BASE = 32'h{SCRATCH_BASE:08x};")
    lines.append(f"  localparam int          SCRATCH_BYTES = {offsets['scratch_bytes']};")
    for key in (
        "x0", "ln1_0", "msa_0", "y_0", "ln2_0", "hidden_0", "ffn_out_0", "z0",
        "x1", "ln1_1", "msa_1", "y_1", "ln2_1", "hidden_1", "ffn_out_1", "z1",
    ):
        lines.append(f"  localparam int {key.upper()}_OFF = {offsets[key + '_off']};")
    lines.append(f"  localparam int LN_BYTES = {192 * tokens};")
    lines.append(f"  localparam int MSA_BYTES = {192 * tokens};")
    lines.append(f"  localparam int Y_BYTES = {192 * tokens};")
    lines.append(f"  localparam int HIDDEN_BYTES = {768 * tokens};")
    lines.append(f"  localparam int FFN_OUT_BYTES = {192 * tokens};")
    lines.append(f"  localparam int Z_ROWS = {z_rows};")
    lines.append(f"  localparam int Z_BYTES = {192 * z_rows};")
    lines.append(f"  localparam int Z0_PAD_OFF = {offsets['z0_off'] + 192 * tokens};")
    lines.append(f"  localparam int Z0_PAD_BYTES = {192 * (z_rows - tokens)};")
    lines.append(f"  localparam int Z1_PAD_OFF = {offsets['z1_off'] + 192 * tokens};")
    lines.append(f"  localparam int Z1_PAD_BYTES = {192 * (z_rows - tokens)};")
    lines.append("")
    for idx, desc in enumerate(descriptors):
        lines.append(f"  localparam logic [319:0] DESC{idx} = 320'h{desc.pack():080x};")
    lines.append("")
    lines.append("  localparam logic signed [5:0] OUT_SCALE = -6'sd7;")
    lines.append("")
    for idx, desc_regions in enumerate(regions):
        for r, (base, size) in enumerate(desc_regions):
            lines.append(
                f"  localparam logic [31:0] D{idx}_R{r}_BASE  = 32'h{base:08x};"
            )
            lines.append(f"  localparam int          D{idx}_R{r}_BYTES = {size};")
    lines.append("")
    lines.append("endpackage")
    lines.append("")
    lines.append("`endif")

    config_path = REPO_ROOT / "sim" / "generated" / "block_tb_config.sv"
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")


def generate_block(seed, tokens, outdir):
    rng = np.random.default_rng(seed)
    n = tokens
    if n < 2 or n > 197:
        raise ValueError("tokens must be in [2, 197]")

    x = [
        [int(v) for v in row]
        for row in rng.integers(-128, 128, size=(n, 192), dtype=np.int64)
    ]
    params0 = _random_block_params(rng)
    params1 = _random_block_params(rng)
    z0, ck0 = transformer_block(x, params0)
    z1, ck1 = transformer_block(z0, params1)

    z_rows = (n + 7) // 8 * 8
    scratch0 = _block_scratch_offsets(n, 0, z_rows)
    scratch1 = _block_scratch_offsets(
        n, scratch0["z"] + scratch0["z_rows_bytes"], z_rows
    )
    scratch1["x"] = scratch0["z"]
    scratch_bytes = align8(scratch1["z"] + scratch1["z_rows_bytes"])

    weight_offsets, weight_bytes = _block_weight_offsets()
    weight_names = (
        "wqkv", "bqkv", "wproj", "bproj", "gamma1", "beta1",
        "w1", "b1", "w2", "b2", "gamma2", "beta2",
    )
    weight0 = {name: weight_offsets[f"{name}0"] for name in weight_names}
    weight1 = {name: weight_offsets[f"{name}1"] for name in weight_names}

    descriptors = (
        _block_descriptors(n, scratch0, weight0)
        + _block_descriptors(n, scratch1, weight1)
    )
    regions = (
        _block_regions(n, scratch0, weight0, z_rows)
        + _block_regions(n, scratch1, weight1, z_rows)
    )

    offsets = {
        "x0_off": scratch0["x"],
        "ln1_0_off": scratch0["ln1"],
        "msa_0_off": scratch0["msa"],
        "y_0_off": scratch0["y"],
        "ln2_0_off": scratch0["ln2"],
        "hidden_0_off": scratch0["hidden"],
        "ffn_out_0_off": scratch0["ffn_out"],
        "z0_off": scratch0["z"],
        "x1_off": scratch1["x"],
        "ln1_1_off": scratch1["ln1"],
        "msa_1_off": scratch1["msa"],
        "y_1_off": scratch1["y"],
        "ln2_1_off": scratch1["ln2"],
        "hidden_1_off": scratch1["hidden"],
        "ffn_out_1_off": scratch1["ffn_out"],
        "z1_off": scratch1["z"],
        "scratch_bytes": scratch_bytes,
        "weight_bytes": weight_bytes,
    }
    write_block_sv_config(outdir, tokens, offsets, descriptors, regions)

    x_path = outdir / "input.mem"
    write_mem(x_path, pack_int8_bytes([v for row in x for v in row]))

    weight_parts = []
    for params in (params0, params1):
        weight_parts += [
            pack_int8_bytes([v for row in params.mhsa.wqkv for v in row]),
            pack_int32_bytes(params.mhsa.bqkv),
            pack_int8_bytes([v for row in params.mhsa.wproj for v in row]),
            pack_int32_bytes(params.mhsa.bproj),
            pack_int8_bytes(params.mhsa.ln_gamma),
            pack_int8_bytes(params.mhsa.ln_beta),
            pack_int8_bytes([v for row in params.ffn.w1 for v in row]),
            pack_int32_bytes(params.ffn.b1),
            pack_int8_bytes([v for row in params.ffn.w2 for v in row]),
            pack_int32_bytes(params.ffn.b2),
            pack_int8_bytes(params.ffn.ln_gamma),
            pack_int8_bytes(params.ffn.ln_beta),
        ]
    weight_path = outdir / "weight.mem"
    weight_words = [word for part in weight_parts for word in part]
    write_mem(weight_path, weight_words)

    descriptors_path = outdir / "descriptors.mem"
    write_descriptors_mem(descriptors_path, descriptors)

    checkpoint_names = ("ln1", "msa", "y", "ln2", "hidden", "ffn_out", "z")
    checkpoint_paths = {}
    for block, (z_out, ck) in ((0, (z0, ck0)), (1, (z1, ck1))):
        for name in checkpoint_names:
            flat = [v for row in ck[name] for v in row]
            if name == "z":
                flat += [0xA5] * (192 * (z_rows - n))
            path = outdir / f"b{block}_{name}_expected.mem"
            checkpoint_paths[f"b{block}_{name}"] = path
            write_mem(path, pack_int8_bytes(flat))

    files = [
        {
            "name": "input.mem",
            "records": len(pack_int8_bytes([v for row in x for v in row])),
            "sha256": sha256_file(x_path),
        },
        {"name": "weight.mem", "records": len(weight_words),
         "sha256": sha256_file(weight_path)},
        {"name": "descriptors.mem", "records": len(descriptors),
         "sha256": sha256_file(descriptors_path)},
    ]
    files += [
        {"name": path.name, "records": 0, "sha256": sha256_file(path)}
        for path in checkpoint_paths.values()
    ]
    manifest = {
        "case": "block",
        "seed": seed,
        "tokens": tokens,
        "generator": "tools/generate_transformer_vectors.py",
        "weight_bytes": weight_bytes,
        "scratch_bytes": scratch_bytes,
        "z_rows": z_rows,
        "scales": {"activation": -7, "weight": 0},
        "descriptors": [
            {"opcode": d.opcode, "hex": f"{d.pack():080x}"} for d in descriptors
        ],
        "files": files,
    }
    with open(outdir / "manifest.json", "w", newline="\n") as handle:
        json.dump(manifest, handle, indent=2)
        handle.write("\n")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--case", required=True,
                        choices=["patch", "mhsa", "ffn", "block"])
    parser.add_argument("--tokens", type=int, default=197)
    parser.add_argument("--seed", type=int, required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    outdir = args.output
    if not outdir.is_absolute():
        outdir = REPO_ROOT / outdir
    if args.case == "patch":
        generate_patch(args.seed, outdir)
    elif args.case == "mhsa":
        generate_mhsa(args.seed, args.tokens, outdir)
    elif args.case == "ffn":
        generate_ffn(args.seed, args.tokens, outdir)
    else:
        generate_block(args.seed, args.tokens, outdir)
    print(f"generated {args.case} vectors -> {outdir}")


if __name__ == "__main__":
    main()
