`timescale 1ns / 1ps

// Task 4: stable compaction and single-Package finalize through the tensor
// executor.
//
// Runs the six deterministic unit cases generated by
// tools/generate_selector_vectors.py --suite unit (keep_all, prune_all,
// mixed, threshold_eq, incoming_package, zero_den). Per case the input
// tokens are segment-loaded, the fused scores are backdoor-written, and one
// OP_SELECTOR_FINALIZE descriptor runs. The output bytes are compared
// against the golden output.mem, the atomic state update must fire exactly
// once with the expected next_token_count/next_package_present, warning
// pulse bit 1 must fire only for the zero-denominator case, and output
// guard bytes beyond the written rows must keep their 0xA5 sentinel.
module tb_selector_finalize;
  import heatvit_pkg::*;
  import tb_pkg::*;

  localparam logic [31:0] SCRATCH_BASE  = 32'h02000000;
  localparam int          SCRATCH_BYTES = 131072;

  logic        clk   = 1'b0;
  logic        rst_n = 1'b0;

  logic [7:0]  token_count;
  logic        pkg_present_in;
  logic        abort;
  logic        desc_valid;
  logic        desc_ready;
  heatvit_desc_t desc_d;
  logic        busy;
  logic        done;
  logic        error_valid;
  logic [7:0]  error_code;
  logic        abort_done;
  logic [2:0]  warning_pulse;
  logic        state_update_valid;
  logic [7:0]  next_token_count;
  logic        next_package_present;

  logic        mem_cmd_valid;
  logic        mem_cmd_ready;
  logic        mem_cmd_write;
  logic [31:0] mem_cmd_addr;
  logic [15:0] mem_cmd_len;
  logic        mem_w_valid;
  logic        mem_w_ready;
  logic [63:0] mem_w_data;
  logic [7:0]  mem_w_strb;
  logic        mem_w_last;
  logic        mem_r_valid;
  logic        mem_r_ready;
  logic [63:0] mem_r_data;
  logic        mem_r_last;

  logic        obs_cmd_valid;
  logic        obs_cmd_write;
  logic [31:0] obs_cmd_addr;
  logic [15:0] obs_cmd_len;
  logic        dbg_valid;
  logic        dbg_ready;
  logic [31:0] dbg_addr;
  logic [7:0]  dbg_data;
  logic        dbg_w_valid;
  logic [31:0] dbg_w_addr;
  logic [7:0]  dbg_w_data;
  logic        load_valid;
  logic        load_ready;
  logic [1:0]  load_seg;
  logic [31:0] load_bytes;
  string       load_file;

  logic [15:0] stall_mask;
  string       stall_str;
  logic [15:0] parsed_mask;

  heatvit_tensor_executor dut (
    .clk                   (clk),
    .rst_n                 (rst_n),
    .abort                 (abort),
    .desc_valid            (desc_valid),
    .desc_ready            (desc_ready),
    .desc                  (desc_d),
    .current_token_count   (token_count),
    .current_package_present(pkg_present_in),
    .input_base            (32'h00000000),
    .input_bytes           (32'd0),
    .weight_base           (32'h01000000),
    .weight_bytes          (32'd0),
    .scratch_base          (SCRATCH_BASE),
    .scratch_bytes         (SCRATCH_BYTES),
    .output_base           (32'h03000000),
    .output_bytes          (32'd0),
    .busy                  (busy),
    .done                  (done),
    .error_valid           (error_valid),
    .error_code            (error_code),
    .abort_done            (abort_done),
    .warning_pulse         (warning_pulse),
    .state_update_valid    (state_update_valid),
    .next_token_count      (next_token_count),
    .next_package_present  (next_package_present),
    .mem_cmd_valid         (mem_cmd_valid),
    .mem_cmd_ready         (mem_cmd_ready),
    .mem_cmd_write         (mem_cmd_write),
    .mem_cmd_addr          (mem_cmd_addr),
    .mem_cmd_len           (mem_cmd_len),
    .mem_w_valid           (mem_w_valid),
    .mem_w_ready           (mem_w_ready),
    .mem_w_data            (mem_w_data),
    .mem_w_strb            (mem_w_strb),
    .mem_w_last            (mem_w_last),
    .mem_r_valid           (mem_r_valid),
    .mem_r_ready           (mem_r_ready),
    .mem_r_data            (mem_r_data),
    .mem_r_last            (mem_r_last)
  );

  // Invariant: state_update_valid may only assert together with done. The
  // scheduler samples both on the same cycle, so a lone pulse would be lost.
  always @(posedge clk) begin
    if (state_update_valid && !done) begin
      tb_fatal("state_update_valid pulsed without done");
    end
  end

  behavioral_memory #(
    .SEG_COUNT  (1),
    .SEG0_FILE  (""),
    .SEG0_BASE  (SCRATCH_BASE),
    .SEG0_BYTES (SCRATCH_BYTES),
    .LFSR_INIT  (16'hF00D)
  ) dut_mem (
    .clk          (clk),
    .rst_n        (rst_n),
    .stall_mask   (stall_mask),
    .mem_cmd_valid(mem_cmd_valid),
    .mem_cmd_ready(mem_cmd_ready),
    .mem_cmd_write(mem_cmd_write),
    .mem_cmd_addr (mem_cmd_addr),
    .mem_cmd_len  (mem_cmd_len),
    .mem_w_valid  (mem_w_valid),
    .mem_w_ready  (mem_w_ready),
    .mem_w_data   (mem_w_data),
    .mem_w_strb   (mem_w_strb),
    .mem_w_last   (mem_w_last),
    .mem_r_valid  (mem_r_valid),
    .mem_r_ready  (mem_r_ready),
    .mem_r_data   (mem_r_data),
    .mem_r_last   (mem_r_last),
    .obs_cmd_valid(obs_cmd_valid),
    .obs_cmd_write(obs_cmd_write),
    .obs_cmd_addr (obs_cmd_addr),
    .obs_cmd_len  (obs_cmd_len),
    .dbg_valid    (dbg_valid),
    .dbg_ready    (dbg_ready),
    .dbg_addr     (dbg_addr),
    .dbg_data     (dbg_data),
    .dbg_w_valid  (dbg_w_valid),
    .dbg_w_addr   (dbg_w_addr),
    .dbg_w_data   (dbg_w_data),
    .load_valid   (load_valid),
    .load_ready   (load_ready),
    .load_seg     (load_seg),
    .load_bytes   (load_bytes),
    .load_file    (load_file)
  );

  always #5 clk = ~clk;

  int          i;
  int          state_pulses;
  int          warn_pulses;
  logic [7:0]  got_byte;
  logic [63:0] exp_out [0:(197 * 192) / 8 - 1];
  logic [63:0] score_words [0:(197 * 4) / 8];
  string       vector_dir;
  string       case_name;
  int          case_n;
  int          case_pkg_in;
  int          case_next;
  int          case_pkg_out;
  int          case_warn;
  int          c_count;
  int          tok_off, score_off, out_off;

  task automatic dbg_w(input logic [31:0] addr, input logic [7:0] data);
    dbg_w_valid = 1'b1;
    dbg_w_addr  = addr;
    dbg_w_data  = data;
    @(posedge clk);
    #1;
    dbg_w_valid = 1'b0;
  endtask

  task automatic dbg_rd(input logic [31:0] addr, output logic [7:0] data);
    dbg_valid = 1'b1;
    dbg_addr  = addr;
    @(posedge clk);
    #1;
    data = dbg_data;
    dbg_valid = 1'b0;
  endtask

  task automatic load_segment(
    input logic [1:0]  seg,
    input int          bytes,
    input string       file
  );
    load_seg   = seg;
    load_bytes = bytes;
    load_file  = file;
    load_valid = 1'b1;
    wait (load_ready);
    @(posedge clk);
    #1;
    load_valid = 1'b0;
  endtask

  task automatic run_desc(input logic [319:0] word);
    desc_d     = word;
    desc_valid = 1'b1;
    wait (desc_ready);
    @(posedge clk);
    #1;
    desc_valid = 1'b0;
    wait (done || error_valid);
    #1;
    if (error_valid) begin
      $display("descriptor error code=%0d", error_code);
      tb_fatal("finalize descriptor reported an error");
    end
  endtask

  task automatic setup_case(input string name,
                            input int n, pkg_in, next_n, pkg_out, warn);
    int fd;
    case_name = name;
    case_n    = n;
    case_pkg_in  = pkg_in;
    case_next   = next_n;
    case_pkg_out = pkg_out;
    case_warn   = warn;
    c_count    = n - 1;
    tok_off    = 0;
    score_off  = n * 192;
    out_off    = (score_off + c_count * 4 + 7) & ~7;

    fd = $fopen({vector_dir, "/", name, "/tokens.mem"}, "r");
    if (fd == 0) begin
      $display("missing vector: %s/tokens.mem", name);
      tb_fatal("finalize vectors missing");
    end
    $fclose(fd);
    fd = $fopen({vector_dir, "/", name, "/output.mem"}, "r");
    if (fd == 0) begin
      $display("missing vector: %s/output.mem", name);
      tb_fatal("finalize vectors missing");
    end
    $fclose(fd);
  endtask

  task automatic run_case();
    heatvit_desc_t d;
    int c;

    token_count    = case_n[7:0];
    pkg_present_in = case_pkg_in[0];

    load_segment(2'd0, tok_off + case_n * 192,
                 {vector_dir, "/", case_name, "/tokens.mem"});
    $readmemh({vector_dir, "/", case_name, "/scores.mem"}, score_words);
    for (c = 0; c < c_count; c++) begin
      dbg_w(SCRATCH_BASE + score_off + c * 4 + 0,
            score_words[c / 2][8 * ((c % 2) * 4) +: 8]);
      dbg_w(SCRATCH_BASE + score_off + c * 4 + 1,
            score_words[c / 2][8 * ((c % 2) * 4 + 1) +: 8]);
      dbg_w(SCRATCH_BASE + score_off + c * 4 + 2,
            score_words[c / 2][8 * ((c % 2) * 4 + 2) +: 8]);
      dbg_w(SCRATCH_BASE + score_off + c * 4 + 3, 8'h00);
    end
    $readmemh({vector_dir, "/", case_name, "/output.mem"}, exp_out);
    // Sentinel-fill the whole output region.
    for (i = out_off; i < out_off + case_n * 192; i++)
      dbg_w(SCRATCH_BASE + i, 8'ha5);

    d = '0;
    d.opcode      = OP_SELECTOR_FINALIZE;
    d.flags       = (1 << FLAG_DYNAMIC_M) | (1 << FLAG_SRC1_SCRATCH);
    d.n           = 16'd192;
    d.src0_offset = tok_off;
    d.src1_offset = score_off;
    d.dst_offset  = out_off;
    d.param0      = DYN_M_CURRENT;
    run_desc(d);

    @(posedge clk);
    #1;
    if (next_token_count != case_next[7:0]) begin
      $display("%s next_token_count=%0d expected=%0d", case_name,
               next_token_count, case_next);
      tb_fatal("finalize token count mismatch");
    end
    if (next_package_present != case_pkg_out[0]) begin
      $display("%s next_package_present=%b expected=%b", case_name,
               next_package_present, case_pkg_out);
      tb_fatal("finalize package present mismatch");
    end

    // Compare the output rows byte for byte.
    for (i = 0; i < case_next * 192; i++) begin
      dbg_rd(SCRATCH_BASE + out_off + i, got_byte);
      if (got_byte !== exp_out[i / 8][8 * (i % 8) +: 8]) begin
        $display("%s output byte %0d mismatch: got=%h want=%h", case_name,
                 i, got_byte, exp_out[i / 8][8 * (i % 8) +: 8]);
        tb_fatal("finalize output mismatch");
      end
    end
    // Guard bytes beyond the written rows keep the sentinel.
    for (i = case_next * 192; i < case_n * 192; i++) begin
      dbg_rd(SCRATCH_BASE + out_off + i, got_byte);
      if (got_byte !== 8'ha5) begin
        $display("%s guard byte %0d modified: got=%h", case_name, i,
                 got_byte);
        tb_fatal("finalize guard byte modified");
      end
    end
  endtask

  function automatic logic [7:0] sat8_div(input int num, input int den);
    int mag;
    int quot;
    int rem_;
    int res;
    mag  = (num < 0) ? -num : num;
    quot = mag / den;
    rem_ = mag % den;
    if (2 * rem_ >= den) quot = quot + 1;
    res = (num < 0) ? -quot : quot;
    if (res > 127) res = 127;
    if (res < -128) res = -128;
    return res[7:0];
  endfunction

  // Row byte of a 192-byte row streamed from a flat byte view.
  function automatic logic [7:0] flat_row_byte(
      input logic [63:0] arr [0:(197 * 192) / 8 - 1],
      input int row, input int col);
    int idx;
    idx = row * 192 + col;
    return arr[idx / 8][8 * (idx % 8) +: 8];
  endfunction

  // ---------------------------------------------------------------
  // Chained finalize: three consecutive OP_SELECTOR_FINALIZE runs where
  // each output becomes the next input and the trailing Package is the
  // last candidate of the following stage.
  // ---------------------------------------------------------------
  localparam logic [31:0] CHAIN_S2 = 32'h00004000;  // stage-2 scores
  localparam logic [31:0] CHAIN_O2 = 32'h00005000;  // stage-2 output
  localparam logic [31:0] CHAIN_S3 = 32'h00006000;  // stage-3 scores
  localparam logic [31:0] CHAIN_O3 = 32'h00007000;  // stage-3 output

  logic [7:0] chain_exp [0:9 * 192 - 1];  // stage 2 + stage 3 outputs

  task automatic run_chained();
    heatvit_desc_t d;
    int c, dd, k;
    int s2[7];
    int s3[4];
    logic [7:0] chk;

    // Re-load the mixed case as the stage-1 input and run it once more.
    load_segment(2'd0, 12 * 192,
                 {vector_dir, "/mixed/tokens.mem"});
    $readmemh({vector_dir, "/mixed/scores.mem"}, score_words);
    for (c = 0; c < 11; c++) begin
      dbg_w(SCRATCH_BASE + 2304 + c * 4 + 0,
            score_words[c / 2][8 * ((c % 2) * 4) +: 8]);
      dbg_w(SCRATCH_BASE + 2304 + c * 4 + 1,
            score_words[c / 2][8 * ((c % 2) * 4 + 1) +: 8]);
      dbg_w(SCRATCH_BASE + 2304 + c * 4 + 2,
            score_words[c / 2][8 * ((c % 2) * 4 + 2) +: 8]);
      dbg_w(SCRATCH_BASE + 2304 + c * 4 + 3, 8'h00);
    end
    $readmemh({vector_dir, "/mixed/output.mem"}, exp_out);
    token_count    = 8'd12;
    pkg_present_in = 1'b0;
    d = '0;
    d.opcode      = OP_SELECTOR_FINALIZE;
    d.flags       = (1 << FLAG_DYNAMIC_M) | (1 << FLAG_SRC1_SCRATCH);
    d.n           = 16'd192;
    d.src0_offset = 32'd0;
    d.src1_offset = 32'd2304;
    d.dst_offset  = 32'd2352;
    d.param0      = DYN_M_CURRENT;
    run_desc(d);
    @(posedge clk);
    #1;
    if (next_token_count != 8'd8 || next_package_present != 1'b1) begin
      $display("chain stage1 state=%0d/%b", next_token_count,
               next_package_present);
      tb_fatal("chained finalize stage 1 state mismatch");
    end

    // ---- Stage 2: input = stage-1 output (8 rows, Package present). ----
    s2[0] = 50000; s2[1] = 1000; s2[2] = 50000; s2[3] = 1000;
    s2[4] = 50000; s2[5] = 1000; s2[6] = 30000;
    for (c = 0; c < 7; c++) begin
      dbg_w(SCRATCH_BASE + CHAIN_S2 + c * 4 + 0, s2[c][7:0]);
      dbg_w(SCRATCH_BASE + CHAIN_S2 + c * 4 + 1, s2[c][15:8]);
      dbg_w(SCRATCH_BASE + CHAIN_S2 + c * 4 + 2, s2[c][16]);
      dbg_w(SCRATCH_BASE + CHAIN_S2 + c * 4 + 3, 8'h00);
    end
    // Expected stage-2 output: CLS + kept rows 0,2,4 of the six normals
    // (input rows 1,3,5) + one Package.
    for (dd = 0; dd < 192; dd++) chain_exp[0 * 192 + dd] =
        flat_row_byte(exp_out, 0, dd);
    for (dd = 0; dd < 192; dd++) chain_exp[1 * 192 + dd] =
        flat_row_byte(exp_out, 1, dd);
    for (dd = 0; dd < 192; dd++) chain_exp[2 * 192 + dd] =
        flat_row_byte(exp_out, 3, dd);
    for (dd = 0; dd < 192; dd++) chain_exp[3 * 192 + dd] =
        flat_row_byte(exp_out, 5, dd);
    for (dd = 0; dd < 192; dd++) begin
      int num;
      num = 1000 * $signed(flat_row_byte(exp_out, 2, dd)) +
            1000 * $signed(flat_row_byte(exp_out, 4, dd)) +
            1000 * $signed(flat_row_byte(exp_out, 6, dd)) +
            30000 * $signed(flat_row_byte(exp_out, 7, dd));
      chain_exp[4 * 192 + dd] = sat8_div(num, 33000);
    end

    token_count    = 8'd8;
    pkg_present_in = 1'b1;
    d = '0;
    d.opcode      = OP_SELECTOR_FINALIZE;
    d.flags       = (1 << FLAG_DYNAMIC_M) | (1 << FLAG_SRC1_SCRATCH);
    d.n           = 16'd192;
    d.src0_offset = 32'd2352;
    d.src1_offset = CHAIN_S2;
    d.dst_offset  = CHAIN_O2;
    d.param0      = DYN_M_CURRENT;
    run_desc(d);
    @(posedge clk);
    #1;
    if (next_token_count != 8'd5 || next_package_present != 1'b1) begin
      $display("chain stage2 state=%0d/%b", next_token_count,
               next_package_present);
      tb_fatal("chained finalize stage 2 state mismatch");
    end
    for (i = 0; i < 5 * 192; i++) begin
      dbg_rd(SCRATCH_BASE + CHAIN_O2 + i, got_byte);
      if (got_byte !== chain_exp[i]) begin
        $display("chain stage2 byte %0d mismatch: got=%h want=%h", i,
                 got_byte, chain_exp[i]);
        tb_fatal("chained finalize stage 2 output mismatch");
      end
    end

    // ---- Stage 3: input = stage-2 output (5 rows, Package present). ----
    s3[0] = 40000; s3[1] = 1000; s3[2] = 40000; s3[3] = 65536;
    for (c = 0; c < 4; c++) begin
      dbg_w(SCRATCH_BASE + CHAIN_S3 + c * 4 + 0, s3[c][7:0]);
      dbg_w(SCRATCH_BASE + CHAIN_S3 + c * 4 + 1, s3[c][15:8]);
      dbg_w(SCRATCH_BASE + CHAIN_S3 + c * 4 + 2, s3[c][16]);
      dbg_w(SCRATCH_BASE + CHAIN_S3 + c * 4 + 3, 8'h00);
    end
    // Expected stage-3 output: CLS + kept rows 0,2 of the three normals
    // (stage-2 rows 1,3) + one Package.
    for (dd = 0; dd < 192; dd++) chain_exp[5 * 192 + dd] =
        chain_exp[0 * 192 + dd];
    for (dd = 0; dd < 192; dd++) chain_exp[6 * 192 + dd] =
        chain_exp[1 * 192 + dd];
    for (dd = 0; dd < 192; dd++) chain_exp[7 * 192 + dd] =
        chain_exp[3 * 192 + dd];
    for (dd = 0; dd < 192; dd++) begin
      int num;
      num = 1000 * $signed(chain_exp[2 * 192 + dd]) +
            65536 * $signed(chain_exp[4 * 192 + dd]);
      chain_exp[8 * 192 + dd] = sat8_div(num, 66536);
    end

    token_count    = 8'd5;
    pkg_present_in = 1'b1;
    d = '0;
    d.opcode      = OP_SELECTOR_FINALIZE;
    d.flags       = (1 << FLAG_DYNAMIC_M) | (1 << FLAG_SRC1_SCRATCH);
    d.n           = 16'd192;
    d.src0_offset = CHAIN_O2;
    d.src1_offset = CHAIN_S3;
    d.dst_offset  = CHAIN_O3;
    d.param0      = DYN_M_CURRENT;
    run_desc(d);
    @(posedge clk);
    #1;
    if (next_token_count != 8'd4 || next_package_present != 1'b1) begin
      $display("chain stage3 state=%0d/%b", next_token_count,
               next_package_present);
      tb_fatal("chained finalize stage 3 state mismatch");
    end
    for (i = 0; i < 4 * 192; i++) begin
      dbg_rd(SCRATCH_BASE + CHAIN_O3 + i, got_byte);
      if (got_byte !== chain_exp[5 * 192 + i]) begin
        $display("chain stage3 byte %0d mismatch: got=%h want=%h", i,
                 got_byte, chain_exp[5 * 192 + i]);
        tb_fatal("chained finalize stage 3 output mismatch");
      end
    end
  endtask

  always_ff @(posedge clk) begin
    if (!rst_n) begin
      state_pulses <= 0;
      warn_pulses  <= 0;
    end else begin
      if (state_update_valid) state_pulses <= state_pulses + 1;
      if (warning_pulse[1]) warn_pulses <= warn_pulses + 1;
    end
  end

  always_ff @(posedge clk) begin
    if (obs_cmd_valid) begin
      if (obs_cmd_addr < SCRATCH_BASE ||
          obs_cmd_addr + {13'd0, obs_cmd_len, 3'b000} >
              SCRATCH_BASE + SCRATCH_BYTES) begin
        $display("trace addr=%h len=%0d outside scratch",
                 obs_cmd_addr, obs_cmd_len);
        tb_fatal("finalize memory trace outside scratch");
      end
    end
  end

  initial begin
    #10000000000;
    $display("WATCHDOG: busy=%0d", busy);
    tb_fatal("tb_selector_finalize watchdog");
  end

  initial begin
    abort      = 1'b0;
    desc_valid = 1'b0;
    desc_d     = '0;
    token_count = 8'd0;
    pkg_present_in = 1'b0;
    dbg_valid  = 1'b0;
    dbg_addr   = 32'h00000000;
    dbg_w_valid = 1'b0;
    dbg_w_addr  = 32'h00000000;
    dbg_w_data  = 8'h00;
    load_valid = 1'b0;
    load_seg   = 2'd0;
    load_bytes = 32'd0;
    load_file  = "";
    for (i = 0; i < (197 * 192) / 8; i++) exp_out[i] = 64'h0000000000000000;
    for (i = 0; i <= (197 * 4) / 8; i++)
      score_words[i] = 64'h0000000000000000;

    if (!$value$plusargs("STALL_MASK=%s", stall_str)) stall_str = "0";
    if ($sscanf(stall_str, "%h", parsed_mask) != 1) parsed_mask = 16'h0000;
    stall_mask = parsed_mask;

    if (!$value$plusargs("VECTOR_DIR=%s", vector_dir))
      vector_dir = "sim/vectors/selector";

    repeat (4) @(posedge clk);
    rst_n = 1'b1;
    @(posedge clk);
    #1;

    setup_case("keep_all",          8, 0,  8, 0, 0);
    run_case();
    setup_case("prune_all",         8, 0,  2, 1, 0);
    run_case();
    setup_case("mixed",            12, 0,  8, 1, 0);
    run_case();
    setup_case("threshold_eq",      6, 0,  5, 1, 0);
    run_case();
    setup_case("incoming_package",  8, 1,  4, 1, 0);
    run_case();
    setup_case("zero_den",          6, 0,  2, 1, 1);
    run_case();

    run_chained();

    @(posedge clk);
    #1;
    if (state_pulses != 9) begin
      $display("state_update_valid pulses=%0d expected=9", state_pulses);
      tb_fatal("finalize state update pulse count mismatch");
    end
    if (warn_pulses != 1) begin
      $display("warning pulses=%0d expected=1", warn_pulses);
      tb_fatal("finalize warning pulse count mismatch");
    end

    $display("TEST_PASS tb_selector_finalize");
    $finish;
  end

endmodule
